parameters:
    derafu.content.config:
        title: 'Derafu Content'
        url: 'https://www.derafu.dev'
        plugins:
            academy: ~
            api: ~
            blog: ~
            docs: ~
            faq: ~
            # pages: ~
            # search: ~
            # sitemap: ~
            storage: ~

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Derafu\Content\Contract\ContentServiceInterface:
        class: Derafu\Content\ContentService

    Derafu\Content\Contract\ContentContextInterface:
        class: Derafu\Content\ContentContext

    Derafu\Content\Contract\ContentConfigInterface:
        class: Derafu\Content\ContentConfig
        arguments:
            $config: '%derafu.content.config%'

    Derafu\Content\Contract\PluginLoaderInterface:
        class: Derafu\Content\PluginLoader

    Derafu\Content\Contract\ContentLoaderInterface:
        class: Derafu\Content\ContentLoader
        arguments:
            $basePath: '%kernel.project_dir%'

    Derafu\Content\Plugin\Academy\AcademyController:
        public: true

    Derafu\Content\Plugin\Api\ApiController:
        public: true

    Derafu\Content\Plugin\Blog\BlogController:
        public: true

    Derafu\Content\Plugin\Docs\DocsController:
        public: true

    Derafu\Content\Plugin\Faq\FaqController:
        public: true

    Derafu\Content\Plugin\Search\SearchController:
        public: true

    Derafu\Content\Plugin\Storage\StorageController:
        public: true
