<?php

declare(strict_types=1);

/**
 * Derafu: Content - Where knowledge becomes product.
 *
 * Copyright (c) 2025 Esteban De La Fuente Rubio / Derafu <https://www.derafu.dev>
 * Licensed under the MIT License.
 * See LICENSE file for more details.
 */

namespace Derafu\Content\Plugin\Mcp\Tool;

use Derafu\Content\Contract\ContentServiceInterface;
use Derafu\Content\Plugin\Search\SearchPlugin;
use InvalidArgumentException;
use Mcp\Exception\ToolCallException;
use Throwable;

/**
 * MCP tool that asks a natural-language question and gets a conversational
 * answer generated by the LLM configured in the "search" plugin, grounded on
 * the indexed content (the same LLM proxy used by the website's chat widget).
 *
 * Unlike search_content/get_content, which only read from the indexed
 * content, this tool depends on the quality of whatever LLM backend answers
 * it. That is why it is opt-in (see McpPlugin::askEnabled()): a bad or failed
 * answer here makes the whole MCP server look unreliable, even though the
 * rest of the tools never touch an LLM at all.
 */
class AskTool
{
    /**
     * Constructor.
     *
     * @param ContentServiceInterface $contentService Content service.
     */
    public function __construct(
        private readonly ContentServiceInterface $contentService
    ) {
    }

    /**
     * Ask a natural-language question about the content of the website.
     *
     * @param string $question Natural language question.
     * @return string Answer generated by the LLM.
     */
    public function __invoke(string $question): string
    {
        try {
            $plugin = $this->contentService->plugin('search');
        } catch (InvalidArgumentException $e) {
            throw new ToolCallException(
                'The search engine is not configured for this site.',
                previous: $e
            );
        }

        assert($plugin instanceof SearchPlugin);

        $llm = $plugin->llm();

        if ($llm === null) {
            throw new ToolCallException(
                'The "ask" tool is enabled but no LLM backend is configured.'
            );
        }

        try {
            return $llm->query($question);
        } catch (Throwable $e) {
            throw new ToolCallException(sprintf(
                'The LLM backend failed to answer: %s',
                $e->getMessage()
            ), previous: $e);
        }
    }
}
