<?php

declare(strict_types=1);

/**
 * Derafu: Content - Where knowledge becomes product.
 *
 * Copyright (c) 2025 Esteban De La Fuente Rubio / Derafu <https://www.derafu.dev>
 * Licensed under the MIT License.
 * See LICENSE file for more details.
 */

namespace Derafu\Content\Plugin\Search\Contract;

use Derafu\Content\Plugin\Search\Exception\SearchUpstreamException;

/**
 * Client that answers a natural-language question grounded on the indexed
 * content, delegating to whatever LLM backend is configured.
 *
 * The default implementation, OpenAiCompatibleLlmClient, talks to any
 * backend exposing an OpenAI-compatible chat completions endpoint (OpenAI,
 * OpenRouter, Open WebUI, Anthropic through its OpenAI-compatible endpoint,
 * Groq, Ollama, etc.). A different backend that does not speak that
 * protocol (e.g. a provider's native API) can be supported by providing
 * another implementation of this interface, without touching the callers
 * (SearchController, the "ask" MCP tool).
 */
interface LlmClientInterface
{
    /**
     * Ask a natural-language question and get the generated answer.
     *
     * @param string $question The question to ask.
     * @return string The answer generated by the LLM.
     * @throws SearchUpstreamException If the LLM backend fails or returns an
     * unexpected response.
     */
    public function query(string $question): string;
}
