################################################################################
# Routes for all the plugins with available controllers
################################################################################

# ------------------------------------------------------------------------------
# Storage (need to be before the content routes)
# ------------------------------------------------------------------------------

content_storage_download:
  path: /{type}/{uri:.+}/_attachments/{attachment:.+}
  handler: 'Derafu\Content\Plugin\Storage\StorageController::download'

# ------------------------------------------------------------------------------
# API
# ------------------------------------------------------------------------------

content_api:
  path: /api/content.json
  handler: 'Derafu\Content\Plugin\Api\ApiController::index'

# ------------------------------------------------------------------------------
# Academy
# ------------------------------------------------------------------------------

academy:
  path: /academy
  handler: 'Derafu\Content\Plugin\Academy\AcademyController::index'

academy_tag:
  path: /academy/tags/{tag}
  handler: 'Derafu\Content\Plugin\Academy\AcademyController::tag'

academy_lesson:
  path: /academy/{course}/{module}/{lesson}
  handler: 'Derafu\Content\Plugin\Academy\AcademyController::lesson'

academy_module:
  path: /academy/{course}/{module}
  handler: 'Derafu\Content\Plugin\Academy\AcademyController::module'

academy_course:
  path: /academy/{course}
  handler: 'Derafu\Content\Plugin\Academy\AcademyController::course'


# ------------------------------------------------------------------------------
# Blog
# ------------------------------------------------------------------------------

blog:
  path: /blog
  handler: 'Derafu\Content\Plugin\Blog\BlogController::index'

blog_tag:
  path: /blog/tags/{tag}
  handler: 'Derafu\Content\Plugin\Blog\BlogController::tag'

blog_archive:
  path: /blog/archive/{archive}
  handler: 'Derafu\Content\Plugin\Blog\BlogController::archive'

blog_rss:
  path: /blog/rss.xml
  handler: 'Derafu\Content\Plugin\Blog\BlogController::rss'

blog_post:
  path: /blog/{post:.+}
  handler: 'Derafu\Content\Plugin\Blog\BlogController::show'

# ------------------------------------------------------------------------------
# Documentation
# ------------------------------------------------------------------------------

docs:
  path: /docs
  handler: 'Derafu\Content\Plugin\Docs\DocsController::show'
  defaults:
    doc: index

docs_tag:
  path: /docs/tags/{tag}
  handler: 'Derafu\Content\Plugin\Docs\DocsController::tag'

docs_doc:
  path: /docs/{doc:.+}
  handler: 'Derafu\Content\Plugin\Docs\DocsController::show'

# ------------------------------------------------------------------------------
# FAQ
# ------------------------------------------------------------------------------

faq:
  path: /faq
  handler: 'Derafu\Content\Plugin\Faq\FaqController::show'
  defaults:
    question: index

faq_tag:
  path: /faq/tags/{tag}
  handler: 'Derafu\Content\Plugin\Faq\FaqController::tag'

faq_question:
  path: /faq/{question:.+}
  handler: 'Derafu\Content\Plugin\Faq\FaqController::show'
